DROP TABLE IF EXISTS PIECE;
CREATE TABLE IF NOT EXISTS PIECE (
    ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    PIE_TYPE VARCHAR (7),
    PIE_NOMBRE TINYINT UNSIGNED,
    PRIMARY KEY(ID)
)
ENGINE = INNODB;

EXPLAIN PIECE;


INSERT INTO 
PIECE (PIE_TYPE, PIE_NOMBRE)
VALUES 
    ('Piece',1),
    ('Piece',2),
    ('Piece',3),
    ('Piece',4),
    ('Piece',5),
    ('Piece',6),
    ('Piece',7),
    ('Piece',8);
SELECT * FROM PIECE;


SELECT * FROM PIECE WHERE (PIE_NOMBRE = 7) OR (PIE_NOMBRE = 6) ORDER BY PIE_NOMBRE DESC;
